version: '3'

services:
  app:
    build: .
    ports:
      - "5000:80"
    volumes:
      - ./:/var/www
    networks:
      - network-eotica
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - .docker/dbdata:/var/lib/postgresql
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: api_eotica
    networks:
      - network-eotica

networks:
  network-eotica:
    driver: bridge

