version: "3.7"
services:
  app:
    build:
      args:
        user: pedro
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: eotica
    container_name: eotica-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - eotica

  db:
    image: mysql:5.7
    container_name: eotica-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: api_eotica
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_PASSWORD: root
      MYSQL_USER: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - eotica

  nginx:
    image: nginx:alpine
    container_name: eotica-nginx
    restart: unless-stopped
    ports:
      - 8010:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - eotica

networks:
  eotica:
    driver: bridge
